from os import getenv


GENERATION_FREQ = float(getenv("HYPOTHESIS_FAKER_GENERATION_FREQ", "3600"))
GENERATION_TIME = float(getenv("HYPOTHESIS_FAKER_GENERATION_TIME", "1"))
MAX_ITEMS = int(getenv("HYPOTHESIS_FAKER_MAX_ITEMS", "100_000"))
